nelmio_api_doc:
    documentation:
        info:
            title: API plateforme
            description: Documentation de L'API plateforme
            version: 1.0.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Authorization: Bearer {jwt}'
                name: Authorization
                in: header
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /articles except /api/doc
