api_auth_login:
    path: /api/auth/login
    methods:  [POST]
    
api:
    prefix: /api
    resource: '../src/Controller/Api'

gesdinet_jwt_refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh

logout:
    path: /logout